# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build for Android

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
    - name: Get Latest Release
      id: release
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: Cache Gradle and Build
#      uses: actions/cache@v4
#      with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#          ${{ github.workspace }}/common/build
#          ${{ github.workspace }}/android/build
#        key: ${{ runner.os }}-gradle-android
#        restore-keys: |
#          ${{ runner.os }}-gradle-android
    - name: Build with Gradle
      run: |
        ./gradlew :android:packageRelease
        ./gradlew --stop
    - name: Upload Logs
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: ${{ github.workspace }}/android/build/outputs/logs/
    - name: Check Output Exists
      run: ls -laR ${{ github.workspace }}/android/build/outputs/apk/
    - name: Rename APK
      run: |
        cd ${{ github.workspace }}/android/build/outputs/apk/release
        APK_FILE=$(ls *.apk | head -n 1)
        mv "$APK_FILE" bifrost_android_${{ steps.release.outputs.release }}.apk
    - name: Upload APK
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Bifrost
        path: ${{ github.workspace }}/android/build/outputs/apk/release/bifrost_android_${{ steps.release.outputs.release }}.apk
    - name: Upload Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ github.workspace }}/android/build/outputs/apk/release/bifrost_android_${{ steps.release.outputs.release }}.apk
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        replacesArtifacts: false
        omitBodyDuringUpdate: true
        tag: ${{ steps.release.outputs.release }}
